// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Mt.Core;
using SanXing.Data.Models;
using System.Linq;

namespace SanXing.Data.Service
{
    public interface IBlogService
    {
        Blog Single(int ID);

        void Delete(Blog entity);

        IPagedList<Blog> GetAll(int pageIndex, int pageSize, bool showHidden = false);

        void Insert(Blog entity);

        void Update(Blog entity);

        IQueryable<Blog> GetAll();
    }
}


