// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FluentValidation;

namespace SanXing.ViewModels.Validator
{
    public class ContactValidator : AbstractValidator<ContactModel>
    {
        public ContactValidator()
        {
            //RuleFor(x => x.Name)
            //      .NotEmpty().WithMessage("请输入联系人");
        }
    }
}
