// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FluentValidation;

namespace SanXing.ViewModels.Validator
{
    public class CostValidator : AbstractValidator<CostModel>
    {
        public CostValidator()
        {
            RuleFor(x => x.CostDate)
                  .NotEmpty().WithMessage("请输入费用时间");

            RuleFor(x => x.CostTypeID)
              .NotEmpty().WithMessage("请选择费用类别");

            RuleFor(x => x.Money)
                .NotEmpty().WithMessage("请输入金额")
                .GreaterThan(0).WithMessage("请输入大于0的金额");

            RuleFor(x => x.Description)
             .NotEmpty().WithMessage("请输入费用描述");
        }
    }
}
