// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class BlogTypeService : IBlogTypeService
    {

        #region Fields

        private readonly IRepository<BlogType> _BlogTypeRepository;

        #endregion

        #region Ctor

        public BlogTypeService(IRepository<BlogType> BlogTypeRepository
           )
        {
            this._BlogTypeRepository = BlogTypeRepository;

        }

        #endregion

        public BlogType Single(int ID)
        {
            if (ID == 0)
                return null;

            return _BlogTypeRepository.GetById(ID);
        }

        public void Delete(BlogType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("BlogType");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<BlogType> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _BlogTypeRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<BlogType>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<BlogType> GetAll()
        {
            return _BlogTypeRepository.Table;
        }

        public void Insert(BlogType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("BlogType");
            _BlogTypeRepository.Insert(entity);
        }

        public void Update(BlogType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("BlogType");

            _BlogTypeRepository.Update(entity);
        }
    }
}


