// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class BlogService : IBlogService
    {

        #region Fields

        private readonly IRepository<Blog> _BlogRepository;

        #endregion

        #region Ctor

        public BlogService(IRepository<Blog> BlogRepository
           )
        {
            this._BlogRepository = BlogRepository;

        }

        #endregion

        public Blog Single(int ID)
        {
            if (ID == 0)
                return null;

            return _BlogRepository.GetById(ID);
        }

        public void Delete(Blog entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Blog");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<Blog> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _BlogRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<Blog>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<Blog> GetAll()
        {
            return _BlogRepository.Table;
        }

        public void Insert(Blog entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Blog");
            _BlogRepository.Insert(entity);
        }

        public void Update(Blog entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Blog");

            _BlogRepository.Update(entity);
        }
    }
}


