// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class ContactService : IContactService
    {

        #region Fields

        private readonly IRepository<Contact> _ContactRepository;

        #endregion

        #region Ctor

        public ContactService(IRepository<Contact> ContactRepository
           )
        {
            this._ContactRepository = ContactRepository;

        }

        #endregion

        public Contact Single(int ID)
        {
            if (ID == 0)
                return null;

            return _ContactRepository.GetById(ID);
        }

        public void Delete(Contact entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Contact");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<Contact> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _ContactRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<Contact>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<Contact> GetAll()
        {
            return _ContactRepository.Table;
        }

        public void Insert(Contact entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Contact");
            _ContactRepository.Insert(entity);
        }

        public void Update(Contact entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Contact");

            _ContactRepository.Update(entity);
        }
    }
}


