// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class ContactRecordService : IContactRecordService
    {

        #region Fields

        private readonly IRepository<ContactRecord> _ContactRecordRepository;

        #endregion

        #region Ctor

        public ContactRecordService(IRepository<ContactRecord> ContactRecordRepository
           )
        {
            this._ContactRecordRepository = ContactRecordRepository;

        }

        #endregion

        public ContactRecord Single(int ID)
        {
            if (ID == 0)
                return null;

            return _ContactRecordRepository.GetById(ID);
        }

        public void Delete(ContactRecord entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ContactRecord");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<ContactRecord> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _ContactRecordRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<ContactRecord>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<ContactRecord> GetAll()
        {
            return _ContactRecordRepository.Table;
        }

        public void Insert(ContactRecord entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ContactRecord");
            _ContactRecordRepository.Insert(entity);
        }

        public void Update(ContactRecord entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ContactRecord");

            _ContactRecordRepository.Update(entity);
        }
    }
}


