// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class ContactWayService : IContactWayService
    {

        #region Fields

        private readonly IRepository<ContactWay> _ContactWayRepository;

        #endregion

        #region Ctor

        public ContactWayService(IRepository<ContactWay> ContactWayRepository
           )
        {
            this._ContactWayRepository = ContactWayRepository;

        }

        #endregion

        public ContactWay Single(int ID)
        {
            if (ID == 0)
                return null;

            return _ContactWayRepository.GetById(ID);
        }

        public void Delete(ContactWay entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ContactWay");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<ContactWay> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _ContactWayRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<ContactWay>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<ContactWay> GetAll()
        {
            return _ContactWayRepository.Table;
        }

        public void Insert(ContactWay entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ContactWay");
            _ContactWayRepository.Insert(entity);
        }

        public void Update(ContactWay entity)
        {
            if (entity == null)
                throw new ArgumentNullException("ContactWay");

            _ContactWayRepository.Update(entity);
        }
    }
}


