// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class CostTypeService : ICostTypeService
    {

        #region Fields

        private readonly IRepository<CostType> _CostTypeRepository;

        #endregion

        #region Ctor

        public CostTypeService(IRepository<CostType> CostTypeRepository
           )
        {
            this._CostTypeRepository = CostTypeRepository;

        }

        #endregion

        public CostType Single(int ID)
        {
            if (ID == 0)
                return null;

            return _CostTypeRepository.GetById(ID);
        }

        public void Delete(CostType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CostType");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<CostType> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _CostTypeRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<CostType>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<CostType> GetAll()
        {
            return _CostTypeRepository.Table;
        }

        public void Insert(CostType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CostType");
            _CostTypeRepository.Insert(entity);
        }

        public void Update(CostType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("CostType");

            _CostTypeRepository.Update(entity);
        }
    }
}


