// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class CostService : ICostService
    {

        #region Fields

        private readonly IRepository<Cost> _CostRepository;

        #endregion

        #region Ctor

        public CostService(IRepository<Cost> CostRepository
           )
        {
            this._CostRepository = CostRepository;

        }

        #endregion

        public Cost Single(int ID)
        {
            if (ID == 0)
                return null;

            return _CostRepository.GetById(ID);
        }

        public void Delete(Cost entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Cost");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<Cost> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _CostRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<Cost>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<Cost> GetAll()
        {
            return _CostRepository.Table;
        }

        public void Insert(Cost entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Cost");
            _CostRepository.Insert(entity);
        }

        public void Update(Cost entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Cost");

            _CostRepository.Update(entity);
        }
    }
}


