// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class PlanService : IPlanService
    {

        #region Fields

        private readonly IRepository<Plan> _PlanRepository;

        #endregion

        #region Ctor

        public PlanService(IRepository<Plan> PlanRepository
           )
        {
            this._PlanRepository = PlanRepository;

        }

        #endregion

        public Plan Single(int ID)
        {
            if (ID == 0)
                return null;

            return _PlanRepository.GetById(ID);
        }

        public void Delete(Plan entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Plan");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<Plan> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _PlanRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<Plan>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<Plan> GetAll()
        {
            return _PlanRepository.Table;
        }

        public void Insert(Plan entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Plan");
            _PlanRepository.Insert(entity);
        }

        public void Update(Plan entity)
        {
            if (entity == null)
                throw new ArgumentNullException("Plan");

            _PlanRepository.Update(entity);
        }
    }
}


