// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class RichTypeService : IRichTypeService
    {

        #region Fields

        private readonly IRepository<RichType> _RichTypeRepository;

        #endregion

        #region Ctor

        public RichTypeService(IRepository<RichType> RichTypeRepository
           )
        {
            this._RichTypeRepository = RichTypeRepository;

        }

        #endregion

        public RichType Single(int ID)
        {
            if (ID == 0)
                return null;

            return _RichTypeRepository.GetById(ID);
        }

        public void Delete(RichType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("RichType");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<RichType> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _RichTypeRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<RichType>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<RichType> GetAll()
        {
            return _RichTypeRepository.Table;
        }

        public void Insert(RichType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("RichType");
            _RichTypeRepository.Insert(entity);
        }

        public void Update(RichType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("RichType");

            _RichTypeRepository.Update(entity);
        }
    }
}


