// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class TimeCostTypeService : ITimeCostTypeService
    {

        #region Fields

        private readonly IRepository<TimeCostType> _TimeCostTypeRepository;

        #endregion

        #region Ctor

        public TimeCostTypeService(IRepository<TimeCostType> TimeCostTypeRepository
           )
        {
            this._TimeCostTypeRepository = TimeCostTypeRepository;

        }

        #endregion

        public TimeCostType Single(int ID)
        {
            if (ID == 0)
                return null;

            return _TimeCostTypeRepository.GetById(ID);
        }

        public void Delete(TimeCostType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("TimeCostType");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<TimeCostType> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _TimeCostTypeRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<TimeCostType>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<TimeCostType> GetAll()
        {
            return _TimeCostTypeRepository.Table;
        }

        public void Insert(TimeCostType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("TimeCostType");
            _TimeCostTypeRepository.Insert(entity);
        }

        public void Update(TimeCostType entity)
        {
            if (entity == null)
                throw new ArgumentNullException("TimeCostType");

            _TimeCostTypeRepository.Update(entity);
        }
    }
}


