// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class TimeCostService : ITimeCostService
    {

        #region Fields

        private readonly IRepository<TimeCost> _TimeCostRepository;

        #endregion

        #region Ctor

        public TimeCostService(IRepository<TimeCost> TimeCostRepository
           )
        {
            this._TimeCostRepository = TimeCostRepository;

        }

        #endregion

        public TimeCost Single(int ID)
        {
            if (ID == 0)
                return null;

            return _TimeCostRepository.GetById(ID);
        }

        public void Delete(TimeCost entity)
        {
            if (entity == null)
                throw new ArgumentNullException("TimeCost");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<TimeCost> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _TimeCostRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<TimeCost>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<TimeCost> GetAll()
        {
            return _TimeCostRepository.Table;
        }

        public void Insert(TimeCost entity)
        {
            if (entity == null)
                throw new ArgumentNullException("TimeCost");
            _TimeCostRepository.Insert(entity);
        }

        public void Update(TimeCost entity)
        {
            if (entity == null)
                throw new ArgumentNullException("TimeCost");

            _TimeCostRepository.Update(entity);
        }
    }
}


