// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using Mt.Core;
using Mt.Core.Data;
using SanXing.Data.Models;
using SanXing.Data.Service;

namespace SanXing.Data.Impl
{
    public partial class UserService : IUserService
    {

        #region Fields

        private readonly IRepository<User> _UserRepository;

        #endregion

        #region Ctor

        public UserService(IRepository<User> UserRepository
           )
        {
            this._UserRepository = UserRepository;

        }

        #endregion

        public User Single(int ID)
        {
            if (ID == 0)
                return null;

            return _UserRepository.GetById(ID);
        }

        public void Delete(User entity)
        {
            if (entity == null)
                throw new ArgumentNullException("User");

            entity.Deleted = true;
            Update(entity);
        }

        public IPagedList<User> GetAll(int pageIndex, int pageSize, bool showHidden = false)
        {
            var query = _UserRepository.Table;
            if (!showHidden)
                query = query.Where(a => !a.Deleted);
            query = query.OrderByDescending(a => a.ID);

            var result = new PagedList<User>(query, pageIndex, pageSize);
            return result;
        }

        public IQueryable<User> GetAll()
        {
            return _UserRepository.Table;
        }

        public void Insert(User entity)
        {
            if (entity == null)
                throw new ArgumentNullException("User");
            _UserRepository.Insert(entity);
        }

        public void Update(User entity)
        {
            if (entity == null)
                throw new ArgumentNullException("User");

            _UserRepository.Update(entity);
        }
    }
}


