//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXing.Data.Models
{
    using System;
    using System.Collections.Generic;
    using Mt.Core;
    using System.ComponentModel;

    [Description("博客类型")]
    public partial class BlogType : BaseEntity
    {

        public BlogType()
        {
            this.Blog = new HashSet<Blog>();
            this.ChildCates = new HashSet<BlogType>();
        }

        public string CateName { get; set; }
        public int? PID { get; set; }
        public string Code { get; set; }
        public int Level { get; set; }
        public int UserID { get; set; }
        public bool Deleted { get; set; }


        public virtual BlogType PCate { get; set; }
        public virtual ICollection<BlogType> ChildCates { get; set; }
        public virtual ICollection<Blog> Blog { get; set; }
        public virtual User User { get; set; }

    }
}
