//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXing.Data.Models
{
    using System;
    using System.Collections.Generic;
    using Mt.Core;
    using System.ComponentModel;

    [Description("联系人")]
    public partial class Contact : BaseEntity
    {

        public Contact()
        {
            this.ContactRecord = new HashSet<ContactRecord>();
        }

        public string Name { get; set; }
        public bool Sex { get; set; }
        public int Age { get; set; }
        public string Avtar { get; set; }
        public string Advantages { get; set; }
        public string Weakness { get; set; }
        public string Mettle { get; set; }
        public string Description { get; set; }
        public int RichTypeID { get; set; }
        public int ContactScore { get; set; }
        public int ContactTypeID { get; set; }
        public string Pinyin { get; set; }
        public int UserID { get; set; }
        public bool Deleted { get; set; }


        public virtual RichType RichType { get; set; }
        public virtual ContactType ContactType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ContactRecord> ContactRecord { get; set; }
    }
}
