//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXing.Data.Models
{
    using System;
    using System.Collections.Generic;
    using Mt.Core;
    using System.ComponentModel;

    [Description("富裕程度")]
    public partial class RichType : BaseEntity
    {
        public RichType()
        {
            this.Contact = new HashSet<Contact>();
            this.ChildCates = new HashSet<RichType>();
        }

        public string CateName { get; set; }
        public int? PID { get; set; }
        public string Code { get; set; }
        public int Level { get; set; }
        public bool Deleted { get; set; }

        public virtual RichType PCate { get; set; }
        public virtual ICollection<RichType> ChildCates { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }

    }
}
