//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXing.Data.Models
{
    using System;
    using System.Collections.Generic;
    using Mt.Core;
    using System.ComponentModel;

    [Description("游戏")]
    public partial class User : BaseEntity
    {
        public User()
        {
            this.BlogType = new HashSet<BlogType>();
            this.Blog = new HashSet<Blog>();
            this.Contact = new HashSet<Contact>();
            this.ContactRecord = new HashSet<ContactRecord>();
            this.Cost = new HashSet<Cost>();
            this.TimeCost = new HashSet<TimeCost>();
        }

        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime LastTime { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public int ActiveStatus { get; set; }
        public bool Deleted { get; set; }


        public virtual ICollection<BlogType> BlogType { get; set; }

        public virtual ICollection<Blog> Blog { get; set; }

        public virtual ICollection<Contact> Contact { get; set; }

        public virtual ICollection<ContactRecord> ContactRecord { get; set; }

        public virtual ICollection<Cost> Cost { get; set; }

        public virtual ICollection<TimeCost> TimeCost { get; set; }
    }
}
