// <autogenerated>
//   This file was generated by T4 code generator Main.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AutoMapper;
using Mt.Core.Infrastructure;
using SanXing.Data.Models;

namespace SanXing.ViewModels
{
    public class AutoMapperStartupTask : IStartupTask
    {

        public void Execute()
        {

            Mapper.CreateMap<ContactRecord, ContactRecordModel>();
            Mapper.CreateMap<ContactRecordModel, ContactRecord>();

            Mapper.CreateMap<ContactType, ContactTypeModel>();
            Mapper.CreateMap<ContactTypeModel, ContactType>();

            Mapper.CreateMap<Cost, CostModel>();
            Mapper.CreateMap<CostModel, Cost>();

            Mapper.CreateMap<Plan, PlanModel>();
            Mapper.CreateMap<PlanModel, Plan>();

            Mapper.CreateMap<User, UserModel>();
            Mapper.CreateMap<UserModel, User>();

            Mapper.CreateMap<Contact, ContactModel>();
            Mapper.CreateMap<ContactModel, Contact>();

            Mapper.CreateMap<Blog, BlogModel>();
            Mapper.CreateMap<BlogModel, Blog>();

            Mapper.CreateMap<TimeCost, TimeCostModel>();
            Mapper.CreateMap<TimeCostModel, TimeCost>();

            Mapper.CreateMap<ContactWay, ContactWayModel>();
            Mapper.CreateMap<ContactWayModel, ContactWay>();

            Mapper.CreateMap<CostType, CostTypeModel>();
            Mapper.CreateMap<CostTypeModel, CostType>();

            Mapper.CreateMap<RichType, RichTypeModel>();
            Mapper.CreateMap<RichTypeModel, RichType>();

            Mapper.CreateMap<BlogType, BlogTypeModel>();
            Mapper.CreateMap<BlogTypeModel, BlogType>();

            Mapper.CreateMap<TimeCostType, TimeCostTypeModel>();
            Mapper.CreateMap<TimeCostTypeModel, TimeCostType>();

        }

        public int Order
        {
            get { return 0; }
        }
    }
}
