//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXing.ModelDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRecord
    {
        public int ID { get; set; }
        public string ContactID { get; set; }
        public int ContactWayID { get; set; }
        public string Problem { get; set; }
        public string Description { get; set; }
        public string Sentiment { get; set; }
        public string Score { get; set; }
        public string CreateTime { get; set; }
        public int UserID { get; set; }
        public int ContactID1 { get; set; }
    
        public virtual ContactWay ContactWay { get; set; }
        public virtual User User { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
