//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXing.ModelDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ReadSublime = new HashSet<Blog>();
            this.Contact = new HashSet<Contact>();
            this.Cost = new HashSet<Cost>();
            this.ContactRecord = new HashSet<ContactRecord>();
            this.SublimeType = new HashSet<BlogType>();
            this.TimeCost = new HashSet<TimeCost>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string CreateTime { get; set; }
        public string LastTime { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string ActiveStatus { get; set; }
    
        public virtual ICollection<Blog> ReadSublime { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Cost> Cost { get; set; }
        public virtual ICollection<ContactRecord> ContactRecord { get; set; }
        public virtual ICollection<BlogType> SublimeType { get; set; }
        public virtual ICollection<TimeCost> TimeCost { get; set; }
    }
}
